### ISSUE TITLE
Can't construct custom dataset

### ISSUE THREAD

**Issue by ekarais** [rusty1s/pytorch_geometric#1305]
## 🐛 Bug

Hello! I am attempting to create my own custom dataset. Following the tutorial in https://pytorch-geometric.readthedocs.io/en/latest/notes/create_dataset.html, I created my own dataset class in the following way:

```python
class MyPGM(InMemoryDataset):
    
    def __init__(self, root, size, transform=None, pre_transform=None):
        super(MyPGM, self).__init__(root, transform, pre_transform)
        self.data, self.slices = torch.load(self.processed_paths[0])
        self.size = size
        self.data_dir = "/home/username/Documents/bthesis/data/onehot/neutral_" + str(self.size) + "/"
        assert os.path.isdir(self.data_dir)
        
    def raw_file_names(self):
        return []
            
    def processed_file_names(self):
        return ['data.pt']
            
    def download(self):
        pass
            
    def process(self):
        data_list = []
        
        edge_index = torch.empty(2, 56)
        c = 0
        for i in range(8):
            for j in range(8):
                if i != j:
                    edge_index[:,c] = [i,j]
                    c += 1
        
        for filename in os.listdir(self.data_dir):
            RPM = np.load(self.data_dir + filename)
            x = torch.from_numpy(RPM[:8*336].reshape(8,336))
            y = torch.from_numpy(RPM[-29:].reshape(1,29))
            data = Data(x=x, edge_index=edge_index, y=y)
            data_list.append(data)
            
        data, slices = self.collate(data_list)
        torch.save((data, slices), self.processed_paths[0])
```

When I try to initialize my dataset, I get the following error output:

```shell
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-eae73a5cecdf> in <module>
----> 1 dataset = MyPGM(root="/home/username/Documents/bthesis/data/proto/", size=256000)

<ipython-input-2-8910e5248ac2> in __init__(self, root, size, transform, pre_transform)
      2 
      3     def __init__(self, root, size, transform=None, pre_transform=None):
----> 4         super(MyPGM, self).__init__(root, transform, pre_transform)
      5         self.data, self.slices = torch.load(self.processed_paths[0])
      6         self.size = size

~/miniconda3/envs/bthesis/lib/python3.7/site-packages/torch_geometric/data/in_memory_dataset.py in __init__(self, root, transform, pre_transform, pre_filter)
     52                  pre_filter=None):
     53         super(InMemoryDataset, self).__init__(root, transform, pre_transform,
---> 54                                               pre_filter)
     55         self.data, self.slices = None, None
     56 

~/miniconda3/envs/bthesis/lib/python3.7/site-packages/torch_geometric/data/dataset.py in __init__(self, root, transform, pre_transform, pre_filter)
     88 
     89         if 'download' in self.__class__.__dict__.keys():
---> 90             self._download()
     91 
     92         if 'process' in self.__class__.__dict__.keys():

~/miniconda3/envs/bthesis/lib/python3.7/site-packages/torch_geometric/data/dataset.py in _download(self)
    136 
    137     def _download(self):
--> 138         if files_exist(self.raw_paths):  # pragma: no cover
    139             return
    140 

~/miniconda3/envs/bthesis/lib/python3.7/site-packages/torch_geometric/data/dataset.py in raw_paths(self)
    126         r"""The filepaths to find in order to skip the download."""
    127         files = to_list(self.raw_file_names)
--> 128         return [osp.join(self.raw_dir, f) for f in files]
    129 
    130     @property

~/miniconda3/envs/bthesis/lib/python3.7/site-packages/torch_geometric/data/dataset.py in <listcomp>(.0)
    126         r"""The filepaths to find in order to skip the download."""
    127         files = to_list(self.raw_file_names)
--> 128         return [osp.join(self.raw_dir, f) for f in files]
    129 
    130     @property

~/miniconda3/envs/bthesis/lib/python3.7/posixpath.py in join(a, *p)
     92                 path += sep + b
     93     except (TypeError, AttributeError, BytesWarning):
---> 94         genericpath._check_arg_types('join', a, *p)
     95         raise
     96     return path

~/miniconda3/envs/bthesis/lib/python3.7/genericpath.py in _check_arg_types(funcname, *args)
    151         else:
    152             raise TypeError('%s() argument must be str or bytes, not %r' %
--> 153                             (funcname, s.__class__.__name__)) from None
    154     if hasstr and hasbytes:
    155         raise TypeError("Can't mix strings and bytes in path components") from None

TypeError: join() argument must be str or bytes, not 'method'
```

It seems to me that the `os.path` module does not recognize that `self.raw_dir` is meant to be executed. Perhaps this is related to my Python version?

## Environment

* OS: Ubuntu 18.04
* Python version: 3.7.7 (compiled with GCC 7.3.0)
* PyTorch version: 1.5.0
* CUDA/cuDNN version:10.2.0
* GCC version:7.5.0
* Any other relevant information:

Many thanks!

**Comment by rusty1s** [comment]
The problem is that you are returning an empty list. You can just remove the `download` and `raw_file_names` methods and everything should be working.

**Comment by ekarais** [comment]
Thank you for the quick response! Unfortunately, the same error persists after removing `download` and `raw_file_names`; this time through the `self.processed_dir` method:

```shell
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-8-eae73a5cecdf> in <module>
----> 1 dataset = MyPGM(root="/home/username/Documents/bthesis/data/proto/", size=256000)

<ipython-input-7-d83dffb7b6f9> in __init__(self, root, size, transform, pre_transform)
      2 
      3     def __init__(self, root, size, transform=None, pre_transform=None):
----> 4         super(MyPGM, self).__init__(root, transform, pre_transform)
      5         self.data, self.slices = torch.load(self.processed_paths[0])
      6         self.size = size

~/miniconda3/envs/bthesis/lib/python3.7/site-packages/torch_geometric/data/in_memory_dataset.py in __init__(self, root, transform, pre_transform, pre_filter)
     52                  pre_filter=None):
     53         super(InMemoryDataset, self).__init__(root, transform, pre_transform,
---> 54                                               pre_filter)
     55         self.data, self.slices = None, None
     56 

~/miniconda3/envs/bthesis/lib/python3.7/site-packages/torch_geometric/data/dataset.py in __init__(self, root, transform, pre_transform, pre_filter)
     91 
     92         if 'process' in self.__class__.__dict__.keys():
---> 93             self._process()
     94 
     95     def indices(self):

~/miniconda3/envs/bthesis/lib/python3.7/site-packages/torch_geometric/data/dataset.py in _process(self)
    158                 'delete `{}` first.'.format(self.processed_dir))
    159 
--> 160         if files_exist(self.processed_paths):  # pragma: no cover
    161             return
    162 

~/miniconda3/envs/bthesis/lib/python3.7/site-packages/torch_geometric/data/dataset.py in processed_paths(self)
    133         folder in order to skip the processing."""
    134         files = to_list(self.processed_file_names)
--> 135         return [osp.join(self.processed_dir, f) for f in files]
    136 
    137     def _download(self):

~/miniconda3/envs/bthesis/lib/python3.7/site-packages/torch_geometric/data/dataset.py in <listcomp>(.0)
    133         folder in order to skip the processing."""
    134         files = to_list(self.processed_file_names)
--> 135         return [osp.join(self.processed_dir, f) for f in files]
    136 
    137     def _download(self):

~/miniconda3/envs/bthesis/lib/python3.7/posixpath.py in join(a, *p)
     92                 path += sep + b
     93     except (TypeError, AttributeError, BytesWarning):
---> 94         genericpath._check_arg_types('join', a, *p)
     95         raise
     96     return path

~/miniconda3/envs/bthesis/lib/python3.7/genericpath.py in _check_arg_types(funcname, *args)
    151         else:
    152             raise TypeError('%s() argument must be str or bytes, not %r' %
--> 153                             (funcname, s.__class__.__name__)) from None
    154     if hasstr and hasbytes:
    155         raise TypeError("Can't mix strings and bytes in path components") from None

TypeError: join() argument must be str or bytes, not 'method'
```

**Comment by rusty1s** [comment]
How do you initialize your `dataset`? What is the value of `root`?

**Comment by ekarais** [comment]
```python
dataset = MyPGM(root="/home/username/Documents/bthesis/data/proto/", size=256000)
```

The path I specify for `root` exists in the file system.

**Comment by rusty1s** [comment]
It‘s strange that the `join` call fails. I have no idea why. One of its components seems to not be a string. I think you need to debug why the `[osp.join(root, f) for f in self.processed_file_names()]` call fails.

**Comment by ekarais** [comment]
I think `[osp.join(self.processed_dir, f) for f in files]` is problematic here. Perhaps because of the list comprehension, the `join` call does not recognize `self.processed_dir` as a method to be executed, but rather as a signature to the method itself. Would it be possible to take the method call out of the `join` call and save its output in an intermediate variable instead?

Also, may I ask which Python version you recommend for PyG?

**Comment by rusty1s** [comment]
I see. We test on Python >= 3.6, and I have never witnessed this error by myself on any Python version.

Can you change the list comprehension according to your suggestions and see if that fixes your issue?

**Comment by ekarais** [comment]
Sure, I'll try that tomorrow. Thanks!

**Comment by ekarais** [comment]
I resolved the issue. The problem was that I did not set my `processed_file_names` function as a property, but the code in `dataset.py` assumes this. Thanks a lot!

**Comment by rusty1s** [comment]
Oh, you are right! I missed that. Perfect :)

**Comment by GitHubzhangweizhen** [comment]
hi, i want to implement graph classification ,and now i have three .npy file: 1.A: adjacency matrix  2.X：nodes_features  3.y :Labels，how i can create custom graph into custom datasets???

**Comment by rusty1s** [comment]
Do you have a single graph or a list of graphs? You can read in your data and simply pass them as PyTorch tensors to a PyG `data` object:
```python
x = torch.from_numpy(np.load('node_features.npy')).to(torch.float)
y = torch.from_numpy(np.load('labels.npy')).to(torch.long)
adj = torch.from_numpy(np.load('adjacency.npy'))
edge_index = adj.nonzero(as_tuple=False).t()

data= Data(x=x, y=y, edge_index=edge_index)
```

**Comment by Lim-Sung-Jun** [comment]
> `processed_file_names` function as a property, b

I am able to resolve same problem thanks to you!
could you explain the reason setting the function as property?

**Comment by rusty1s** [comment]
No real reason :) I thought it would be cleaner to have that as a property, so you should definitely take care of adding the `@property` annotation.

**Comment by lucaaamaral** [comment]
I'm having a similar issue. I'm running my code in a set .py files as is:

utils.py
```
from os import listdir, path

import numpy as np
from skimage.io import imread
from skimage.color import gray2rgb, rgba2rgb
from skimage.segmentation import slic
from skimage.graph import RAG, rag_mean_color

from torch_geometric.utils import from_networkx
from torch_geometric.data import Data

from zipfile import ZipFile
import numpy as np


def list_files(dir: str, subdir: str = "") -> list:
    file_names = []
    file_extentions = []

    file_dir = path.join(dir, subdir)
    if not path.exists(file_dir): return []
    for filename in listdir(file_dir):
        if path.isfile(path.join(file_dir, filename)):
            name, extention = path.splitext(filename)
            if extention not in file_extentions:
                file_extentions.append(extention)
            file_names.append(path.join(subdir, filename))
            # file_names.append(name)

    if len(file_extentions) > 1:
        raise AttributeError("More than one file extention detected: " \
                        f"{file_extentions}")
    
    return file_names


def load_image(image_path: str) -> np.ndarray:
    try:
        image = imread(image_path)
    except Exception as e:
        print(f"[ERROR]Troble reading image {image_path}")
        raise TypeError(f"{e}\nTroble reading image {image_path}")

    image_len = len(image.shape)
    if image_len < 2: 
        pass
    if image_len == 2: 
        image = gray2rgb(image)
    elif image_len == 3 and image.shape[2] == 3: 
        pass
    elif image_len == 3 and image.shape[2] == 4: 
        image = rgba2rgb(image)
    else: 
        raise TypeError("Unsupported image shape with length of "\
                        f"{image_len}\n\t\tFound at file {image_path}")

    return image


def load_mask(mask_path: str) -> np.ndarray:
    mask = imread(mask_path)
    binary_mask = np.isin(mask, [1]).astype(bool)
    mask_true = binary_mask.any()
    if not mask_true:
        print(f"Malformed mask {mask_path}")
    return binary_mask


def load_image_data(image_path: str) -> Data:
    full_filename = (path.split(image_path))[1]
    filename = (path.splitext(full_filename))[0]
    
    image = load_image(image_path)
    mask = load_mask(path.join(image_path, "../../trimaps",filename+".png"))

    if filename.isupper(): superclass = 0
    else: superclass = 1

    try:
        segments = slic(image, n_segments=75, compactness=20, mask=mask)
    except Exception as e:
        raise Exception(f"SLIC failure at {filename} with image depth of "\
            f"{len(image.shape)}\n\t{e}")
        
    try:
        rag = rag_mean_color(image, segments)
    except Exception as e:
        raise Exception(f"RAG failure at {filename} with image depth of "\
                f"{len(image.shape)}\n\t{e}")

    data: Data = from_networkx(rag, "all", "all")
    data.y = superclass

    return data


def unzip(zip_file: str, destpath: str) -> None:
    with ZipFile(zip_file, 'r') as zip_ref:
        zip_ref.extractall(destpath)


def time_diff_human(start_time, end_time):
    duration_seconds = end_time - start_time

    days = duration_seconds // (24 * 3600)
    duration_seconds = duration_seconds % (24 * 3600)
    hours = duration_seconds // 3600
    duration_seconds %= 3600
    minutes = duration_seconds // 60
    duration_seconds %= 60
    seconds = duration_seconds // 1
    duration_seconds %= 1
    milisseconds = duration_seconds*1000

    duration_str = ""
    duration_str += f"{int(days)} days, "
    duration_str += f"{int(hours)} hours, "
    duration_str += f"{int(minutes)} minutes, "
    duration_str += f"{int(seconds)} seconds, "
    duration_str += f"{milisseconds:.2f} milisseconds"

    return duration_str
```

ImageData.py
```
from torch_geometric.data import InMemoryDataset
from utils import list_files, load_image_data, unzip, time_diff_human
from multiprocessing import Pool, cpu_count
from shutil import move, rmtree
import os, time

import resource
rlimit = resource.getrlimit(resource.RLIMIT_NOFILE)
resource.setrlimit(resource.RLIMIT_NOFILE, (32384, rlimit[1]))

class ImageData(InMemoryDataset):
    def __init__(self, root: str = None, 
                 log: bool = False, force_reload: bool = False):
        super().__init__(root = root, log = log, force_reload=force_reload)
        if os.path.exists(self.processed_paths[0]):
            self.load(self.processed_paths[0])
        else:
            raise FileNotFoundError(f"Missing file {self.processed_paths[0]}")


    @property
    def raw_file_names(self):
        list_files(self.raw_dir, "trimaps")
        files = list_files(self.raw_dir, "images")
        return files


    @property
    def processed_file_names(self):
        return ["cats_dogs.pt"]


    def download(self) -> None:
        zip_file = os.path.join(os.getcwd(),"datasets", "cats_and_dogs.zip")
        unzip(zip_file, self.raw_dir)

        source = os.path.join(self.raw_dir, "cats_and_dogs", "annotations", "trimaps")
        dest = os.path.join(self.raw_dir, "trimaps")
        move(source, dest)
    
        source = os.path.join(self.raw_dir, "cats_and_dogs", "images")
        dest = os.path.join(self.raw_dir, "images")
        move(source, dest)

        rmtree(os.path.join(self.raw_dir, "cats_and_dogs"))


    def process(self) -> None:
        with Pool(processes=max(1, cpu_count())) as pool:
            data_list = pool.map(load_image_data, self.raw_paths)

        if self.pre_filter is not None:
            data_list = [data for data in data_list if self.pre_filter(data)]

        if self.pre_transform is not None:
            data_list = [self.pre_transform(data) for data in data_list]
        
        if len(data_list) != 0:
            self.save(data_list, self.processed_paths[0])


def main():
    start_time = time.time()
    dataset_root = os.path.join(os.getcwd(),"datasets", "pytorch")
    imagedata = ImageData(dataset_root, True, True)
    end_time = time.time()

    print(f"Total elapsed time: {time_diff_human(start_time, end_time)}")


if __name__ == "__main__":
    main()
```

And the error I'm getting:
```
Traceback (most recent call last):
  File "/home/lucas/Documents/Github/Estudos/exemplos_gnn/library/ImageData.py", line 72, in <module>
    main()
  File "/home/lucas/Documents/Github/Estudos/exemplos_gnn/library/ImageData.py", line 65, in main
    imagedata = ImageData(dataset_root, True, True)
  File "/home/lucas/Documents/Github/Estudos/exemplos_gnn/library/ImageData.py", line 14, in __init__
    super().__init__(root = root, log = log, force_reload=force_reload)
  File "/home/lucas/Documents/Github/Estudos/venv/lib/python3.10/site-packages/torch_geometric/data/in_memory_dataset.py", line 81, in __init__
    super().__init__(root, transform, pre_transform, pre_filter, log,
  File "/home/lucas/Documents/Github/Estudos/venv/lib/python3.10/site-packages/torch_geometric/data/dataset.py", line 112, in __init__
    self._download()
  File "/home/lucas/Documents/Github/Estudos/venv/lib/python3.10/site-packages/torch_geometric/data/dataset.py", line 225, in _download
    if files_exist(self.raw_paths):  # pragma: no cover
  File "/home/lucas/Documents/Github/Estudos/venv/lib/python3.10/site-packages/torch_geometric/data/in_memory_dataset.py", line 318, in __getattr__
    raise AttributeError(f"'{self.__class__.__name__}' object has no "
AttributeError: 'ImageData' object has no attribute 'raw_paths'

```

I am failing to understand where I have done wrong in this script. I'm running it in a python from a venv with all requirements fulfilled.

**Comment by lucaaamaral** [comment]
I've found where it got bad: the `list_files` function trows an error that is not displayed on the screen. As I had no clue what was going on, I've placed many prints in try excepts and discovered this behavior.
