### ISSUE TITLE
SNAPDataset not working

### ISSUE THREAD

**Issue by Magolor** [rusty1s/pytorch_geometric#1716]
## 🐛 Bug

using `torch_geometric.datasets.SNAPDataset` with dataset name "ego-twitter" and "ego-gplus" results in an error.

## To Reproduce

```
import torch_geometric.datasets as DS

data = DS.SNAPDataset("data/",name="ego-gplus")
```

## Expected behavior

e.g.: the "ego-twitter" configuration would lead to:
```
KeyError: 83943787
```

## Environment

* OS: Linux
* Python version: 3.8.3
* PyTorch version: 1.6.0
* CUDA/cuDNN version: 10.1
* GCC version:
* Any other relevant information:

**Comment by rusty1s** [comment]
Seems to be a bug. I will look into it.

**Comment by rusty1s** [comment]
Fixed in master, see https://github.com/rusty1s/pytorch_geometric/commit/c56a50eb2f17a41c4b52d837eb66a44d8efbfee5. Thanks for reporting!

**Comment by Magolor** [comment]
@rusty1s Thank you for your fast reply. The 'ego-twitter' dataset can function now, while the 'ego-gplus' dataset is still facing another error causing by the `uint64`:
```
Traceback (most recent call last):
  File "utils.py", line 79, in <module>
    dataset = DS.SNAPDataset('data/EgoGplus/',name='ego-gplus')
  File ".../lib/python3.8/site-packages/torch_geometric/datasets/snap_dataset.py", line 169, in __init__
    super(SNAPDataset, self).__init__(root, transform, pre_transform,
  File ".../lib/python3.8/site-packages/torch_geometric/data/in_memory_dataset.py", line 53, in __init__
    super(InMemoryDataset, self).__init__(root, transform, pre_transform,
  File ".../lib/python3.8/site-packages/torch_geometric/data/dataset.py", line 92, in __init__
    self._process()
  File ".../lib/python3.8/site-packages/torch_geometric/dat.a/dataset.py", line 165, in _process
    self.process()
  File ".../lib/python3.8/site-packages/torch_geometric/datasets/snap_dataset.py", line 211, in process
    data_list = read_ego(raw_files, self.name[4:])
  File "..../lib/python3.8/site-packages/torch_geometric/datasets/snap_dataset.py", line 42, in read_ego
    x = pandas.read_csv(feat_file, sep=' ', header=None, dtype=np.int64)
  File ".../lib/python3.8/site-packages/pandas/io/parsers.py", line 686, in read_csv
    return _read(filepath_or_buffer, kwds)
  File ".../lib/python3.8/site-packages/pandas/io/parsers.py", line 458, in _read
    data = parser.read(nrows)
  File ".../lib/python3.8/site-packages/pandas/io/parsers.py", line 1186, in read
    ret = self._engine.read(nrows)
  File ".../lib/python3.8/site-packages/pandas/io/parsers.py", line 2145, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 847, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 862, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 941, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 1073, in pandas._libs.parsers.TextReader._convert_column_data
  File "pandas/_libs/parsers.pyx", line 1104, in pandas._libs.parsers.TextReader._convert_tokens
  File "pandas/_libs/parsers.pyx", line 1200, in pandas._libs.parsers.TextReader._convert_with_dtype
  File "pandas/_libs/parsers.pyx", line 1753, in pandas._libs.parsers._try_uint64
OverflowError: Overflow

```

**Comment by rusty1s** [comment]
Should be working now :) Sorry for the inconveniences!
