### ISSUE TITLE
Tensor (inferred) cannot be used as a tuple.

### ISSUE THREAD

**Issue by Duchstf** [rusty1s/pytorch_geometric#2099]
## 🐛 Bug

I'm trying to use torch script to export a geometric model. However, I encountered this error when running `torch.jit.script` on the model. 

```python
RuntimeError: 
Tensor (inferred) cannot be used as a tuple:
  File "/home/dhoang/.local/lib/python3.6/site-packages/torch_geometric/nn/meta.py", line 105
    def forward(self, x, edge_index, edge_attr=None, u=None, batch=None):
        """"""
        row, col = edge_index
                   ~~~~~~~~~~ <--- HERE
        if self.edge_model is not None:
```

@lgray suggested that this should be changed to 

```python
row = edge_index[0]
col = edge_index[1]
```

So I'm wondering if a fixed can be pushed for this. 

## To Reproduce

1. Define an interaction network like this

```python
import torch
import torch_geometric
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

import torch.nn as nn
import torch.nn.functional as F
import torch_geometric.transforms as T
from torch_geometric.nn import EdgeConv, global_mean_pool
from torch.nn import Sequential as Seq, Linear as Lin, ReLU, Sigmoid
from torch_scatter import scatter_mean
from torch_geometric.nn import MetaLayer

node_feat = 3
edge_feat = 1
hidden = 8

class EdgeBlock(torch.nn.Module):
    def __init__(self):
        super(EdgeBlock, self).__init__()
        self.edge_mlp = Seq(Lin(node_feat*2+edge_feat, hidden), 
                            ReLU(),
                            Lin(hidden, hidden),
                            ReLU(),
                            Lin(hidden, hidden),
                            ReLU(),
                            Lin(hidden, edge_feat),
                            Sigmoid())

    def forward(self, src, dest, edge_attr, u, batch):
        out = torch.cat([src, dest, edge_attr], 1)
        return self.edge_mlp(out)

class NodeBlock(torch.nn.Module):
    def __init__(self):
        super(NodeBlock, self).__init__()
        self.node_mlp = Seq(Lin(node_feat+edge_feat, hidden), 
                            ReLU(), 
                            Lin(hidden, hidden),
                            ReLU(),
                            Lin(hidden, node_feat),                        
                            )

    def forward(self, x, edge_index, edge_attr, u, batch):
        row = edge_index[0]
        col = edge_index[1]
        
        out = scatter_mean(edge_attr, col, dim=0, dim_size=x.size(0))
        out = torch.cat([x, out], dim=1)
        return self.node_mlp(out)

class InteractionNetwork(torch.nn.Module):
    def __init__(self):
        super(InteractionNetwork, self).__init__()
        self.interactionnetwork = MetaLayer(EdgeBlock(), NodeBlock(), None)
        
    def forward(self, x, edge_index, edge_attr, batch):
        
        # 1st iteration 
        x, edge_attr, _ = self.interactionnetwork(x, edge_index, edge_attr, None, batch)
        # 2nd iteration (only care about output of EdgeBlock -> edge_attr)
        _, edge_attr, _ = self.interactionnetwork(x, edge_index, edge_attr, None, batch)
        
        return edge_attr

model = InteractionNetwork().to(device)
optimizer = torch.optim.Adam(model.parameters(), lr = 1e-2)
```
2. And then run:

```python
a = torch.jit.script(InteractionNetwork())
```

The error appeared at this step.

## Expected behavior

The model being jittable.

## Environment

Conda environment setup can be seen [here](https://github.com/jmduarte/trackml_gnn_example/blob/main/environment_cpu.yml).

**Comment by rusty1s** [comment]
I see. `MetaLayer` currently isn't jittable. I will look into it.

**Comment by rusty1s** [comment]
Should be fixed in master, see https://github.com/rusty1s/pytorch_geometric/commit/4df312a6459eb195333be39f3e48839adf151288.

**Comment by rtviii** [comment]
```python3

from torch import Tensor
import torch

def some_rotation_op(rotation:Tensor):
  [ Rxz, Ryz, Rzz ] = rotation[:, -1] # <-------- both a list and a tuple formulation fail  
  ...
  return Rxz


torch.jit.script(some_rotation_op, (torch.rand( 3, 3),))
``` 
still fails for me :
`unexpected expression on left-hand side of assignment:
  File "test.py", line 6
def some_rotation_op(rotation:Tensor):
  [ Rxz, Ryz, Rzz ] = rotation[:, -1]
  ~~~~~~~~~~~~~~~ <--- HERE
  ``` in the case of list 
  
  and 
  ```
  Tensor cannot be used as a tuple:
  File "test.py", line 6
def some_rotation_op(rotation:Tensor):
  Rxz, Ryz, Rzz = rotation[:, -1]
                  ~~~~~~~~~~~~~~~ <--- HERE
  ...
  return Rxz
  ``` in the case of tuple

**Comment by rusty1s** [comment]
You would need to define `Rxz` and so on explicitly via `Rxz[0, -1]`.
