### ISSUE TITLE
Any import from `torch_geometric` loads `matplotlib` (and a lot more)

### ISSUE THREAD

**Issue by Linux-cpp-lisp** [rusty1s/pytorch_geometric#2189]
## 🐛 Bug

Because `torch_geometric` imports `*` from `.nn`, which imports `*` from `.models`, which imports all of the models, a lot of unnecessary dependencies get loaded whenever _anything_ is imported from `torch_geometric`.

I came across this behavior because it was filling my logging with `matplotlib` messages, but even with logging disabled it would be good for performance if heavy libraries that do file I/O like `matplotlib` are only loaded if they are needed. This can be particularly important for start-up performance on clusters with networked filesystems.

## To Reproduce

```python
import logging
logging.basicConfig(level=logging.DEBUG)

import torch
from torch_geometric.data import Data

d = Data(x=torch.zeros(10, 3))
print(d)
```
Gives many pages of `matplotlib` debug logging, followed by the expected
```
Data(x=[10, 3])
```

## Expected behavior
That `matplotlib` (and other libraries that aren't necessary for basic functions) won't be loaded for any import from `torch_geometric`, giving an output of just
```
Data(x=[10, 3])
```

## Environment

* OS: Linux
* Python version: 3.8.5 / Anaconda
* PyTorch version: 1.7.1
* CUDA/cuDNN version: N/A
* GCC version: N/A
* Any other relevant information: N/A

**Comment by rusty1s** [comment]
You are right! This should be fixed in master. Thanks!

**Comment by Linux-cpp-lisp** [comment]
Thanks @rusty1s !

When I run my test script, I no longer get `matplotlib` but still get some output (`h5py` from the datasets, I believe):
```
DEBUG:h5py._conv:Creating converter from 7 to 5
DEBUG:h5py._conv:Creating converter from 5 to 7
DEBUG:h5py._conv:Creating converter from 7 to 5
DEBUG:h5py._conv:Creating converter from 5 to 7
Data(x=[10, 3])
```

I realize it would be a breaking change and so would need to be considered quite carefully, but it seems to me that it might be worth not importing `datasets` and `nn.models` automatically, since many many programs that use `torch_geometric` to train their own models on their own datasets do not need the wide variety of models, datasets, and their dependencies to be loaded.

It may also be possible to make `datasets` and `nn.models` lazy-loaded, preventing a breaking change but preventing unnecessary loads — see, for example:

- https://modutil.readthedocs.io/en/latest/#lazy_import
- https://pypi.org/project/lazy-import/
- https://github.com/mnmelo/lazy_import

**Comment by Linux-cpp-lisp** [comment]
(For what it's worth, this is motivated by a real performance issue for me: in general starting Python programs on our cluster is quite slow because of small-file access on the networked filesystem, but `torch_geometric` programs are particularly so — I believe now because of some of these unnecessary model loads/setups.)

**Comment by Linux-cpp-lisp** [comment]
Apparently this exists (if a bit unpleasant to use) in the stdlib for Python >=3.5:

- https://docs.python.org/3/library/importlib.html#importlib.util.LazyLoader
- https://stackoverflow.com/questions/42703908/how-do-i-use-importlib-lazyloader

**Comment by rusty1s** [comment]
Thanks for the pointers! This is something I'm definitely interested about. Are you interested in contributing this feature? Otherwise, I will look into it.

**Comment by Linux-cpp-lisp** [comment]
@rusty1s I've given it a shot in #2199 — let me know what you think.

**Comment by Linux-cpp-lisp** [comment]
Fully resolved in #2199.
