### ISSUE TITLE
PointCNN example is broken after #2691

### ISSUE THREAD

**Issue by vladserkoff** [rusty1s/pytorch_geometric#2881]
## 🐛 Bug

Hi! I'm trying to run this example
https://github.com/rusty1s/pytorch_geometric/blob/master/benchmark/points/point_cnn.py
and it appears to be broken because of the #2691
Now this example breaks with the error:

```python
% python -m points.point_cnn --epochs 1        /pytorch_geometric/benchmark master
Downloading http://vision.princeton.edu/projects/2014/3DShapeNets/ModelNet10.zip
Extracting /pytorch_geometric/benchmark/data/ModelNet10/ModelNet10.zip
Processing...
Done!
Traceback (most recent call last):
  File "/miniconda3/envs/pointcloud-classifier/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/miniconda3/envs/pointcloud-classifier/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/pytorch_geometric/benchmark/points/point_cnn.py", line 61, in <module>
    run(train_dataset, test_dataset, model, args.epochs, args.batch_size, args.lr,
  File "/pytorch_geometric/benchmark/points/train_eval.py", line 26, in run
    train(model, optimizer, train_loader, device)
  File "/pytorch_geometric/benchmark/points/train_eval.py", line 48, in train
    out = model(data.pos, data.batch)
  File "/miniconda3/envs/pointcloud-classifier/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/pytorch_geometric/benchmark/points/point_cnn.py", line 42, in forward
    x = F.relu(self.conv2(x, pos, batch))
  File "/miniconda3/envs/pointcloud-classifier/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/miniconda3/envs/pointcloud-classifier/lib/python3.8/site-packages/torch_geometric/nn/conv/x_conv.py", line 139, in forward
    x = x[col].view(N, K, self.in_channels)
RuntimeError: shape '[12288, 12, 48]' is invalid for input of size 1179648
```

checking out back to 1.7.1 fixes the issue

-------

If I understand correctly, this `edge_index = edge_index[:, ::K]` should really be this `edge_index = edge_index[:, ::self.dilation]`.

**Comment by rusty1s** [comment]
Thanks for letting me know. This is now fixed in master, see https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/nn/conv/x_conv.py#L130

**Comment by vladserkoff** [comment]
That was fast, thanks!

**Comment by tashfin-msu** [comment]
Hi,
Although I added the new lines in the x_conv.py file, I am still getting error.

`File "/......../torch_geometric/nn/conv/x_conv.py", line 139, in forward
    x = x[col].view(N, K, self.in_channels)
RuntimeError: shape '[6144, 12, 48]' is invalid for input of size 589824`
