### ISSUE TITLE
Problems running own example GCN

### ISSUE THREAD

**Issue by StephDocTUM** [rusty1s/pytorch_geometric#2954]
Dear all,

I am running the following code:

```

import torch

from IPython.display import set_matplotlib_formats
from matplotlib import pyplot as plt
import torch.nn.functional as F

#import matplotlib.pyplot as plt
from sklearn.manifold import TSNE

def visualize(h, color):
    z = TSNE(n_components=2).fit_transform(out.detach().cpu().numpy())

    plt.figure(figsize=(10,10))
    plt.xticks([])
    plt.yticks([])

    plt.scatter(z[:, 0], z[:, 1], s=70, c=color, cmap="Set2")
    plt.show()
    
from torch_geometric.data import Data
edge_index = torch.tensor([[0, 1],
                           [1, 0],
                           [1, 2],
                           [2, 1],
                           [3, 0],
                           [1, 3],
                           [4, 2],
                           [3, 4],
                           [1, 4],
                           [0, 5],
                           [6, 5],
                           [7, 3],
                           [8, 1],
                           [5, 8],
                           [3, 7],
                           [5, 7],
                           [0, 6],
                           [2, 6]], dtype=torch.long)
x = torch.tensor([[-1], [0], [1], [1], [-1], [0], [1], [1]], dtype=torch.float)

data = Data(x=x, edge_index=edge_index.t().contiguous(), num_classes=2)#, train_mask=2, test_mask=2, val_mask=2)

from torch_geometric.transforms import NormalizeFeatures


dataset = data

print()
print(f'Dataset: {dataset}:')
print('======================')
print(f'Number of graphs: {len(dataset)}')
print(f'Number of features: {dataset.num_features}')
print(f'Number of classes: {dataset.num_classes}')

#data = dataset[0]  # Get the first graph object.

print()
print(data)
print('===========================================================================================================')

# Gather some statistics about the graph.
print(f'Number of nodes: {data.num_nodes}')
print(f'Number of edges: {data.num_edges}')
print(f'Average node degree: {data.num_edges / data.num_nodes:.2f}')
#print(f'Number of training nodes: {data.train_mask.sum()}')
#print(f'Training node label rate: {int(data.train_mask.sum()) / data.num_nodes:.2f}')
print(f'Contains isolated nodes: {data.contains_isolated_nodes()}')
print(f'Contains self-loops: {data.contains_self_loops()}')
#print(f'Is undirected: {data.is_undirected()}')


from torch_geometric.nn import GCNConv

class GCN(torch.nn.Module):
    def __init__(self, hidden_channels):
        super(GCN, self).__init__()
        torch.manual_seed(12345)
        self.conv1 = GCNConv(dataset.num_features, hidden_channels)
        self.conv2 = GCNConv(hidden_channels, dataset.num_classes)

    def forward(self, x, edge_index):
        x = self.conv1(x, edge_index)
        x = x.relu()
        x = F.dropout(x, p=0.5, training=self.training)
        x = self.conv2(x, edge_index)
        return x

model = GCN(hidden_channels=16)
print(model)


model = GCN(hidden_channels=16)
model.eval()

out = model(data.x, data.edge_index)
visualize(out, color=data.y)


from IPython.display import Javascript  # Restrict height of output cell.
display(Javascript('''google.colab.output.setIframeHeight(0, true, {maxHeight: 300})'''))

model = GCN(hidden_channels=16)
optimizer = torch.optim.Adam(model.parameters(), lr=0.01, weight_decay=5e-4)
criterion = torch.nn.CrossEntropyLoss()

def train():
      model.train()
      optimizer.zero_grad()  # Clear gradients.
      out = model(data.x, data.edge_index)  # Perform a single forward pass.
      loss = criterion(out[data.train_mask], data.y[data.train_mask])  # Compute the loss solely based on the training nodes.
      loss.backward()  # Derive gradients.
      optimizer.step()  # Update parameters based on gradients.
      return loss

def test():
      model.eval()
      out = model(data.x, data.edge_index)
      pred = out.argmax(dim=1)  # Use the class with highest probability.
      test_correct = pred[data.test_mask] == data.y[data.test_mask]  # Check against ground-truth labels.
      test_acc = int(test_correct.sum()) / int(data.test_mask.sum())  # Derive ratio of correct predictions.
      return test_acc


for epoch in range(1, 201):
    loss = train()
    print(f'Epoch: {epoch:03d}, Loss: {loss:.4f}')


test_acc = test()
print(f'Test Accuracy: {test_acc:.4f}')

model.eval()

out = model(data.x, data.edge_index)
visualize(out, color=data.y)
```
    
But receive the following error when running out=model(...=

`
Traceback (most recent call last):

  File "<ipython-input-120-9a6fb7a581c1>", line 24, in <module>
    out = model(data.x, data.edge_index)

  File "/home/neurolab2/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)

  File "<ipython-input-120-9a6fb7a581c1>", line 11, in forward
    x = self.conv1(x, edge_index)

  File "/home/neurolab2/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)

  File "/home/neurolab2/anaconda3/lib/python3.8/site-packages/torch_geometric/nn/conv/gcn_conv.py", line 160, in forward
    edge_index, edge_weight = gcn_norm(  # yapf: disable

  File "/home/neurolab2/anaconda3/lib/python3.8/site-packages/torch_geometric/nn/conv/gcn_conv.py", line 62, in gcn_norm
    deg = scatter_add(edge_weight, col, dim=0, dim_size=num_nodes)

  File "/home/neurolab2/anaconda3/lib/python3.8/site-packages/torch_scatter/scatter.py", line 29, in scatter_add
    return scatter_sum(src, index, dim, out, dim_size)

  File "/home/neurolab2/anaconda3/lib/python3.8/site-packages/torch_scatter/scatter.py", line 21, in scatter_sum
    return out.scatter_add_(dim, index, src)

RuntimeError: index 8 is out of bounds for dimension 0 with size 8

`

**Comment by rusty1s** [comment]
`edge_index` contains an index of `8`. However, `x` only has 8 nodes, while it needs 9 (zero-based indexing).

**Comment by StephDocTUM** [comment]
Yes, right.

Running
`      loss = criterion(out[data.train_mask], data.y[data.train_mask])  # Compute the loss solely based on the training nodes.`
(`data.y[data.train_mask]`)
leads to
`TypeError: 'NoneType' object is not subscriptable`

**Comment by rusty1s** [comment]
In case you do not have a `train_mask`, replacing via
```python
loss = criterion(out, data.y)
```
should fix your issues.

**Comment by StephDocTUM** [comment]
Great. It works now. I would like to construct a brain as a graph. Each node represents a specific region in the brain and each region has an edge to every other region. Each node just gets a certain number as attribute. Having 3000 regions results in a 3000x3000 Adjacency matrix, where only the diagonal entries are 0. and rest is 1. Each regions has a single certain association with another region represented in the edge_attribute.
So:
data.x = [3000,1]
data.edge_index = [2,3000x3000]
data.edge_attr = [3000x3000,1]
data.y = [3000, *]

I am unsure what is exactly meant with * in data.y and what are the values in data.y?
The goal is to learn unsupervised e.g. 2 classes in the brain to one of each region/node belongs to.

Do you think it makes sense to implement that with the above posted code and change data.x, .. to these values?

Best,
Steph

**Comment by rusty1s** [comment]
The * in `data.y = [3000, *]` just means that the shape of `data.y` depends on the given task. If you have a binary classification problem for every node, then `data.y` should have shape `[3000]` holding values in `{ 0, 1 }`.

I think, in theory, your graph creation is correct. However, I'm not sure if learning on the dense adjacency matrix is the best approach to tackle this. One could make this adjacency matrix more sparse by only regions that are spatially near. WDYT?

**Comment by StephDocTUM** [comment]
So, I give every node a value of 0 or 1 in data.y? As a supervised learning approach?
I would like more to do an unsupervised clustering of the nodes. Is that possible?

Yes you are probably right, I guess finding nodes which are conditional independent might be a way for more sparsity.

**Comment by rusty1s** [comment]
Yes, that would be a supervised learning approach. In an unsupervised learning approach, you wouldn't make use of ground-truth labels, and instead utilize something along the line of the ["Deep Graph Infomax"](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/infomax_transductive.py) work.

**Comment by StephDocTUM** [comment]
okay. Would Deep Graph Infomax work with the same type of data input as mentioned earlier?
Is there also something implemented such as an anomaly detection for nodes?
Learning with a lot of normal graphs and use then an anomaly detection for a new graph is "anormal" nodes.

**Comment by rusty1s** [comment]
The current implementation of Deep Graph Infomax operates on single graphs and need to be modified in order to operate on a set of graphs, e.g., by iterating over graph using a `DataLoader`, and corrupting each example individually.

We sadly don't have any examples for anomaly detection yet :(

**Comment by StephDocTUM** [comment]
It would be totally fine in the beginning for only one graph. It works until the testing method

`
def test():
    model.eval()
    z, _, _ = model(data.x, data.edge_index)
    acc = model.test(z[data.train_mask], data.y[data.train_mask],
                     z[data.test_mask], data.y[data.test_mask], max_iter=150)
    return acc`

How do I specify data.y in that unsupervised learning method?

**Comment by rusty1s** [comment]
Here, `data.y` is simply used to validate the performance of the unsupervised node embeddings in a down-stream task (node classification). If you do not have any labels, you cannot apply such down-stream evaluation.

**Comment by StephDocTUM** [comment]
Yes, I see. I would not need a numerical evaluation. But I would need to plot it and evaluate it with the visualisation. That should work as well right?

**Comment by rusty1s** [comment]
Yes, you can directly visualize them via TSNE, which seems sufficient for your use-case. When plotting via matplotlib, you can add labels to each dot in the visualization, or make use of some color to identify node ids.

**Comment by StephDocTUM** [comment]
out.dtach() command in def visualize(h, color) gives me AttributeError: ‘tuple’ object has no attribute ‘detach’ .

`#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Aug 18 14:14:00 2021
"""

import os.path as osp

import torch
import torch.nn as nn
from torch_geometric.datasets import Planetoid
from torch_geometric.nn import GCNConv, DeepGraphInfomax
from torch_geometric.transforms import NormalizeFeatures

import numpy as np





LL = np.load('/home/neurolab2/GCN/sub-20Corr_LL.npy')


np.shape(LL)

from torch_geometric.data import Data

torch.Size([3352*3352, 2])

edge_index = torch.empty([0, 2])
x = torch.empty([0, 1])
edge_attr = torch.empty([0, 1])



counter = 1

for i in range (1,10):
    for j in range (1,10):



        #row = LL[i,:]
        #column = LL[1,:]
        print(i)
        print(j)

        #a = np.array([i, j])

    #c = np.concatenate((c[i,:], a[i,:]), axis=1)

        edge_index_temp = torch.tensor([[i, j]], dtype=torch.long)
        edge_index = torch.cat((edge_index, edge_index_temp))



        x_temp = torch.tensor([[counter]], dtype=torch.float)
        x = torch.cat((x, x_temp))
        counter = counter+1

        corr_value = LL[i,j]

        edge_attr_temp = torch.tensor([[corr_value]], dtype=torch.float)
        edge_attr = torch.cat((edge_attr, edge_attr_temp))



#y = torch.tensor([0, 1, 1, 1, 1, 1, 1, 1, 1], dtype=torch.long)


y = (torch.rand(size=(1,81)) < 0.25).long().squeeze(0)

#y_bool = (torch.rand(size=(1,81)) < 0.25).boolean()
#train_mask = (torch.rand(size=(0,81)) < 0.25).long()
train_mask = (torch.rand(size=(1,81)) < 0.25).long().squeeze(0)
test_mask = (torch.rand(size=(1,81)) < 0.25).long().squeeze(0)



#train_mask = torch.gt(train_mask, 0)
#test_mask = torch.gt(y, 1)


edge_index  =torch.tensor(edge_index, dtype=torch.long)

edge_index = torch.transpose(edge_index, 0, 1)

x_dummy = torch.tensor([[1]])

#x = torch.cat((x, x_temp)) ##need one more entry in x than in edge_index



data_HGG = Data(x=x, y=y, train_mask=train_mask, test_mask=test_mask, edge_attr=edge_attr, edge_index=edge_index)#, train_mask=2, test_mask=2, val_mask=2)
data = data_HGG


class Encoder(nn.Module):
    def __init__(self, in_channels, hidden_channels):
        super(Encoder, self).__init__()
        self.conv = GCNConv(in_channels, hidden_channels, cached=True)
        self.prelu = nn.PReLU(hidden_channels)

    def forward(self, x, edge_index):
        x = self.conv(x, edge_index)
        x = self.prelu(x)
        return x


def corruption(x, edge_index):
    return x[torch.randperm(x.size(0))], edge_index


device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = DeepGraphInfomax(
    hidden_channels=81, encoder=Encoder(1, 81),
    #hidden_channels=512, encoder=Encoder(dataset.num_features, 512),
    
    summary=lambda z, *args, **kwargs: torch.sigmoid(z.mean(dim=0)),
    corruption=corruption).to(device)
#data = dataset[0].to(device)



optimizer = torch.optim.Adam(model.parameters(), lr=0.001)


def train():
    model.train() #wo wird das ausgeführt?
    optimizer.zero_grad()
    pos_z, neg_z, summary = model(data.x, data.edge_index) ###where does model go with data.x,..
    loss = model.loss(pos_z, neg_z, summary)
    loss.backward()
    optimizer.step()
    return loss.item()


def test():
    model.eval()
    z, _, _ = model(data.x, data.edge_index)
    acc = model.test(z[data.train_mask], data.y,
                     z[data.test_mask], data.y, max_iter=150)
    return acc


for epoch in range(1, 301):
    loss = train()
    print('Epoch: {:03d}, Loss: {:.4f}'.format(epoch, loss))
acc = test()
print('Accuracy: {:.4f}'.format(acc))

#model.eval()



# Helper function for visualization.
#%matplotlib inline
import matplotlib.pyplot as plt
from sklearn.manifold import TSNE

def visualize(h, color):
    z = TSNE(n_components=2).fit_transform(*out.detach()*.cpu().numpy())

    plt.figure(figsize=(10,10))
    plt.xticks([])
    plt.yticks([])

    plt.scatter(z[:, 0], z[:, 1], s=70, c=color, cmap="Set2")
    plt.show()



out = model(data.x, data.edge_index)
visualize(out, color='green')`

**Comment by rusty1s** [comment]
That's because `DeepGraphInfomax` returns both positive and negative embeddings, as well as the summary vector. `visualize(out[0], color='green')` should fix this.

**Comment by StephDocTUM** [comment]
I see. still the same error but when I change in def visualize(h, color) h to out it works. Where is h used in the visualize method?

**Comment by rusty1s** [comment]
The `h` argument should be used to create TSNE embeddings (while currently you are using the global `out` embedding).

**Comment by rusty1s** [comment]
As a general rule of thumb, you should avoid for-loops at all cost. Furthermore, concatening lists to tensors inside a for-loop is very expensive, as you will create a lot of intermediate tensors. Moving the `cat` calls outside the for-loops should already speed things up. An even faster version is:
```python
row = torch.arange(3352).view(1, -1).repeat(3352, 1).view(-1)
col = torch.arange(3352).view(-1, 1).repeat(1, 3352).view(-1)
edge_index = torch.stack([row, col], dim=0)
edge_attr = LL[row, col]
```
